version: "3.8"

services:
  mysql_server:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_USER: tasks_user
      MYSQL_PASSWORD: tasks_password
      MYSQL_ROOT_PASSWORD: tasks_root_password