version: "3.8"

services:
  postgres_server:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: tasks_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
