name: Build Flutter Web

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  pages: write
  actions: read
  contents: read

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Create .env file from secrets
        run: |
          echo 'API_URL="${{ secrets.API_URL }}"' > .env
        working-directory: frontend

      - name: Build web
        run: flutter build web
        working-directory: frontend

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
