name: Build Flutter Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Create .env file from secrets
        run: |
          echo 'API_URL="${{ secrets.API_URL }}"' > .env
        working-directory: frontend

      - name: Build web
        run: flutter build web
        working-directory: frontend

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: frontend/build/web
